### ISSUE TITLE
Error: The missing file seems to be part of a third party library

### ISSUE THREAD

**Issue by alexandrtovmach** [mariohmol/ang-jsoneditor#2]
```
ERROR in ./node_modules/ang-jsoneditor/jsoneditor/jsoneditor.component.ts
Module build failed: Error: /home/oleksandr/Projects/free/mongoschema_editor/node_modules/ang-jsoneditor/jsoneditor/jsoneditor.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/oleksandr/Projects/free/mongoschema_editor/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/home/oleksandr/Projects/free/mongoschema_editor/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/components/schema-edit.component/schema-edit.component.ts 24:29-86
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by mariohmol** [comment]
Hi ,

there is a bug in angular-cli and angular 5.

Did u try the ang-jsoneditor v 1.5.7?

What is your angular-cli version? Here i'm using cli 1.2.6 and working pretty good with angular5.

If you use angular cli 1.5 you will have problem with a bunch of modules.

I'm trying to find the issue about it but i cant anymor (passed through it last friday)

**Comment by mariohmol** [comment]
I could reproduce your bug using the latest angular-cli and typescript.

I had to remake this component to be using the ng-packagr style

Tested in another project with ang Angular CLI: 1.7.2, angular 5.2.7 and typescript Version 2.6.2

check `npm i -S ang-jsoneditor@1.5.11`

thanks for reaching out
