### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by grtn316** [mariohmol/ang-jsoneditor#53]
When I attempt to start the application, I am getting this error:

[error] TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\tslib\tslib.js:65:9)
    at C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:115:17
    at C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:314:6
    at C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:3:17
    at Object.<anonymous> (C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:20:22
    at C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:10:17
    at Object.<anonymous> (C:\Users\user\source\repos\AngularJsonEditor\AngularJsonEditor\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:16:3)

**Comment by grtn316** [comment]
Sorry, wrong error

**Comment by mariohmol** [comment]
hi.. do u still have this? is an example  stackblitz or somewhere to see?
