### ISSUE TITLE
Angular production build failing

### ISSUE THREAD

**Issue by kunal105** [mariohmol/ang-jsoneditor#68]
Getting the error below for production angular build ng build --configuration=production
ang-jsoneditor": "^1.9.4",
"jsoneditor": "^8.6.8",

Any ideas? Thanks in advance

**Console and Error stack trace**
ERROR in ./node_modules/ang-jsoneditor/fesm5/ang-jsoneditor.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\SourceControl\TradingWidgets\TradingWidgets.Web\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)

 "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "^8.2.2",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.10.52",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5"
  }

**Comment by mariohmol** [comment]
HI, i'vent seeing this issue..

try to use the newes release 1.10.0 (I updated the jsoneditor and maybe is a fix there? )

**Comment by mariohmol** [comment]
closing without an answer
